---
version: "3"
services:
  little-link:
    image: docker.io/hikariai/littlelink-server:latest
    container_name: littlelink-server
    environment:
      - META_TITLE=Hikariai
      - META_DESCRIPTION=Kevin Yu Link page
      - META_AUTHOR=Kevin Yu
      - THEME=Dark
      - FAVICON_URL=https://objectstorage.ap-tokyo-1.oraclecloud.com/n/nrmjjlvckvsb/b/bucket-20210817-2342/o/littleserver-link202108211630.jpg
      - AVATAR_URL=https://objectstorage.ap-tokyo-1.oraclecloud.com/n/nrmjjlvckvsb/b/bucket-20210817-2342/o/littleserver-link202108211630.jpg
      - AVATAR_2X_URL=https://objectstorage.ap-tokyo-1.oraclecloud.com/n/nrmjjlvckvsb/b/bucket-20210817-2342/o/littleserver-link202108211630.jpg
      - AVATAR_ALT=Kevin Yu Profile Pic
      - NAME=Hikariai
      - BIO=Hey! Just a place where you can connect with me!
      - HUGO=https://www.hikariai.net
      - GITHUB=https://github.com/yqlbu
      - LINKED_IN=http://www.linkedin.com/in/chinglong-kevin-yu
      - DISCORD=https://discord.gg/95K3J3a4
      - EMAIL=kevinyu211@yahoo.com
      - TELEGRAM=https://t.me/hikariai_channel
      - FOOTER=Thanks for stopping by!
      # - TWITTER=
      # - INSTAGRAM=
      # - YOUTUBE=
      # - TWITCH=
      # - TIKTOK=
      # - KIT=
      # - FACEBOOK=
      # - FACEBOOK_MESSENGER=https://facebook.com
      # - PRODUCT_HUNT=https://www.producthunt.com/
      # - SNAPCHAT=https://www.snapchat.com/
      # - SPOTIFY=https://www.spotify.com/
      # - REDDIT=https://www.reddit.com/
      # - MEDIUM=https://medium.com
      # - PINTEREST=https://www.pinterest.com/
      # - EMAIL_ALT=you@example.com
      # - SOUND_CLOUD=https://souncloud.com
      # - FIGMA=https://figma.com
      # - TUMBLR=https://www.tumblr.com/
      # - STEAM=https://steamcommunity.com/
      # - VIMEO=https://vimeo.com/
      # - GOODREADS=https://www.goodreads.com/
      # - SKOOB=https://www.skoob.com.br/
    ports:
      - 3000:3000
    restart: always
    security_opt:
      - no-new-privileges:true
